{{if .Values.testingInterface.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka-queueing.fullname" . }}-testing-interface
  labels:
    {{- include "kafka-queueing.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.testingInterface.replicaCount }}
  selector:
    matchLabels:
      {{- include "kafka-queueing.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "kafka-queueing.fullname" . }}-testing-interface
  template:
    metadata:
      labels:
        {{- include "kafka-queueing.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "kafka-queueing.fullname" . }}-testing-interface
      imagePullSecrets:
        - name: dockerconfigjson-github-com
      containers:
        - name: testing-interface
          image: "{{ .Values.testingInterface.image.repository }}:{{ .Values.testingInterface.image.tag }}"
          imagePullPolicy: Never
          resources:
            {{- toYaml .Values.testingInterface.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-queueing.fullname" . }}-testing-interface
  labels:
    {{- include "kafka-queueing.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.testingInterface.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "kafka-queueing.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kafka-queueing.fullname" . }}-testing-interface
  labels:
    {{- include "kafka-queueing.labels" . | nindent 4 }}
  {{- with .Values.testingInterface.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kafka-queueing.fullname" . }}-testing-interface
  labels:
    {{- include "kafka-queueing.labels" . | nindent 4 }}
data:
  {{- with .Values.testingInterface.application.config }}
  application.yaml: |
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kafka-queueing.fullname" . }}-testing-interface
  labels:
    {{- include "kafka-queueing.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kafka-queueing.fullname" . }}-testing-interface
  labels:
  {{- include "kafka-queueing.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kafka-queueing.fullname" . }}-testing-interface
roleRef:
  kind: Role
  name: {{ include "kafka-queueing.fullname" . }}-testing-interface
  apiGroup: rbac.authorization.k8s.io
{{- end }}