apiVersion: v2
name: kafka-queueing
description: A Helm chart for Kubernetes
type: application

dependencies:
  - name: kafka
    version: "^18.x"
    repository: "https://charts.bitnami.com/bitnami"
  - name: schema-registry
    version: 5.1.4
    repository: https://charts.bitnami.com/bitnami

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "1.16.0"
