name: Build and publish container images

on:
  workflow_dispatch:

  push:
    branches:
      - main
    paths:
      - '**'
env:
  REGISTRY: ghcr.io

jobs:
  build:
    outputs:
      semver: ${{ steps.semver.outputs.new_version }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      # https://github.com/hennejg/github-tag-action
      - name: Calculate next version
        id: semver
        uses: hennejg/github-tag-action@v4.3.1
        with:
          github_token: ${{ secrets.ACTIONS_GITHUB_TOKEN }}
          release_branches: main
          dry_run: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACTIONS_GITHUB_USERNAME }}
          password: ${{ secrets.ACTIONS_GITHUB_TOKEN }}

      - name: Build version ${{ steps.semver.outputs.new_version }}
        run: ./gradlew -Pversion=${{ steps.semver.outputs.new_version }} docker
        working-directory: .

      - name: Publish to GitHub Container Registry
        run: |
          docker tag kafka-queueing/kafka-semaphore:latest ghcr.io/${{ secrets.ACTIONS_GITHUB_USERNAME }}/kafka-queueing/kafka-semaphore:latest
          docker push ghcr.io/${{ secrets.ACTIONS_GITHUB_USERNAME }}/kafka-queueing/kafka-semaphore:latest
          docker tag kafka-queueing/kafka-semaphore:latest ghcr.io/${{ secrets.ACTIONS_GITHUB_USERNAME }}/kafka-queueing/kafka-semaphore:${{ steps.semver.outputs.new_version }}
          docker push ghcr.io/${{ secrets.ACTIONS_GITHUB_USERNAME }}/kafka-queueing/kafka-semaphore:${{ steps.semver.outputs.new_version }}
          
          docker tag kafka-queueing/testing-interface:latest ghcr.io/${{ secrets.ACTIONS_GITHUB_USERNAME }}/kafka-queueing/testing-interface:latest
          docker push ghcr.io/${{ secrets.ACTIONS_GITHUB_USERNAME }}/kafka-queueing/testing-interface:latest
          docker tag kafka-queueing/testing-interface:latest ghcr.io/${{ secrets.ACTIONS_GITHUB_USERNAME }}/kafka-queueing/testing-interface:${{ steps.semver.outputs.new_version }}
          docker push ghcr.io/${{ secrets.ACTIONS_GITHUB_USERNAME }}/kafka-queueing/testing-interface:${{ steps.semver.outputs.new_version }}

      # A hack workaround for https://github.com/rickstaa/action-create-tag/issues/10
      - name: "Change perms on GITHUB_WORKSPACE"
        run: |
          sudo chown -R root:root $GITHUB_WORKSPACE
          sudo chmod -R 0777 $GITHUB_WORKSPACE

      # https://github.com/rickstaa/github-tag-action
      - name: Push version tag ${{ steps.semver.outputs.new_tag }}
        uses: rickstaa/action-create-tag@v1
        with:
          tag: "${{ steps.semver.outputs.new_tag }}"
          message: "Version ${{ steps.semver.outputs.new_version }}"

      # https://github.com/marketplace/actions/automatic-releases
      - name: Release ${{ steps.semver.outputs.new_version }}
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          automatic_release_tag: "latest"
          prerelease: false
          repo_token: "${{ secrets.ACTIONS_GITHUB_TOKEN }}"
          title: "Release ${{ steps.semver.outputs.new_version }}"
